version: 5.{build}

platform: x86

stack:
  - go 110-x86
  - msys

clone_folder: c:\gopath\src\github.com\rqlite\rqlite

environment:
  GOPATH: c:\gopath

install:
  - set BUILD_ENV=gnu
  - if %BUILD_ENV%==gnu  set PATH= C:\MinGW\bin;C:\MinGW\msys\1.0\bin;%PATH%
  - if %BUILD_ENV%==gnu  set MSYSTEM=MINGW32
  - if %BUILD_ENV%==gnu  set MSYS=winsymlinks=lnk

build_script:
  - go version
  - go get ./...
  - go build -i ./...
  - go test -v ./...

after_build:
  - 7z a rqlite-latest-win32.zip %GOPATH%\bin\rq*.exe

artifacts:
  - path: rqlite-latest-win32.zip
    name: rqlite for Windows x86
